name: Build Gradle project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
      - name: Execute Build with Gradle Wrapper
        run: ./gradlew build
